services:
  app:
    build:
      dockerfile: Dockerfile.python
    ports:
      - "8080:8080"
    restart: always
    environment:
      - NEXT_PUBLIC_API_HOST=http://localhost:8080
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=todo_list
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pa55word
    depends_on:
      - postgres
